name: JS Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: "Install API packages"
        uses: actions/setup-node@v2
      - run: npm --prefix ./psi install ./psi
      - name: Use local PSI
        uses: ./psi
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}